### PR TITLE
feat: add `copy to clipboard` button

### LINKED ISSUE #77: Configure Hugo to allow copying code blocks to clipboard
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Many static site generators support a copy-to-clipboard button for code blocks. For example, see a [Material for Mkdocs](https://squidfunk.github.io/mkdocs-material/) example:

- https://johnthagen.github.io/python-blueprint/#installation

GitHub also supports this, for example hover over the code blocks here:

- https://github.com/johnthagen/python-blueprint#dependencies

This is especially useful for new users who want to quickly copy out commands such as the [installation](https://python-poetry.org/docs/master/#installation) command that doesn't all fit on the screen at once.

It doesn't seem like this is something that Hugo supports out of the box unfortunately, but there are several guides on it:

- https://simplernerd.com/hugo-add-copy-to-clipboard-button/
- https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/
- https://discourse.gohugo.io/t/copy-button-to-allow-copying-the-content/36076
- https://digitaldrummerj.me/hugo-add-copy-code-snippet-button/
- https://codepen.io/a-luna/pen/JjYrejL
- https://koki-nakamura22.github.io/blog/2019/10/03/hugo-adding-copy-button/

### PR DESCRIPTION
**Pull request by branchvincent**
Second attempt at #37. My only additions here are 1a336cc: 
* Fix an import from `stimulus` -> `@hotwired/stimulus`
* Replace [`rollup-plugin-svg-import`](https://www.npmjs.com/package/rollup-plugin-svg-import) -> [`@rollup/plugin-image`](https://www.npmjs.com/package/@rollup/plugin-image) since the former was still throwing a [parse error](https://github.com/python-poetry/website/runs/8249098805?check_suite_focus=true#step:5:34)

Closes #77

~EDIT: Just noticed rollup still silently throws a [parse error](https://github.com/python-poetry/website/runs/8249098805?check_suite_focus=true#step:5:34) on the svg although everything functions. Will come back to this later today~ fixed

### CODE REVIEW

**Comment by Secrus** [comment]
Those errors you mentioned were the issue that brought down the prod website back when I did the first iteration of this. I gave up back then, but I hope you can make it work.

**Comment by branchvincent** [comment]
@Secrus I swapped out the rollup plugin and things look good to me now. Would be great if you could also verify

**Review by Secrus — APPROVED** [review]

**Comment by Secrus** [comment]
LGTM, however, my previous attempt looked good as well :rofl:.

**Review by neersighted — APPROVED** [review]

**Comment by johnthagen** [comment]
Can confirm that the clipboard copying is working on https://python-poetry.org/docs/. Great job!

**Pull request merged**
