### PR TITLE
Make documentation sidebar sticky

### PR DESCRIPTION
**Pull request by mkniewallner**
Update sidebar to make it sticky, so that it it always visible when scrolling.

https://user-images.githubusercontent.com/5970971/172135185-5500a1e7-5487-461d-9426-8a9152f31a1b.mp4

### CODE REVIEW

**Comment by mkniewallner** [comment]
It looks like the usage of [pull_request_target](https://github.com/python-poetry/website/blob/main/.github/workflows/deploy-preview.yml#L7) may prevent the correct commit from being deployed, since what's getting deployed is the last commit from the main branch, according to https://github.com/python-poetry/website/runs/6754863239?check_suite_focus=true#step:10:19.

So the preview unfortunately doesn't work as expected, and shows the same thing as in `main` branch.

**Comment by abn** [comment]
@mkniewallner you need to add the following to the checkout step.

```yaml
ref: ${{ github.event.pull_request.head.sha }}
```

**Comment by abn** [comment]
Relabled to re-deploy the code. Your preview link should be now using the PR code.

**Comment by abn** [comment]
Is there anything we can do to make the scrollbar (eg: commands doc) more in line with the website styling?

**Comment by mkniewallner** [comment]
> Is there anything we can do to make the scrollbar (eg: commands doc) more in line with the website styling?

The scrollbar is the same as the main scrollbar of the page (no styling, so it will match the user browser/system).
I'm not against styling, but AFAIK a lot of other websites also prefer to keep the user browser/system, to ensure that people get a coherent experience across websites, even for side menus (for instance, [Tailwind's own documentation](https://tailwindcss.com/docs/installation) does that).

One thing we could improve on the PR is that the horizontal position of the scrollbar will match the text that has the largest size. On the `Commands` documentation, that makes the scrollbar pretty far compared to other commands like `Configuration` for instance.

**Comment by abn** [comment]
I am okay with us improving this later. Using system scrollbars end up kinda ruining the site for users on chrome / gnome it seems, granted it appears better on Firefox.

image

**Comment by mkniewallner** [comment]
> I am okay with us improving this later. Using system scrollbars end up kinda ruining the site for users on chrome / gnome it seems, granted it appears better on Firefox.
> 
> image

Indeed, this is quite ugly 😅 
I must say I have only tested that on Firefox/Gnome and Chrome/macOS. Curious about how [Tailwind's documentation](https://tailwindcss.com/docs/installation) looks on Chrome/Gnome though.

**Comment by mkniewallner** [comment]
Added https://github.com/python-poetry/website/pull/47/commits/7284414da3388383b5fc6275872e58004935ebf6 to dynamically update `color-scheme` when switching between light and dark theme, so that scrollbars match the selected theme.

Screenshot from 2022-06-07 21-15-19

It makes the scrollbar way more bearable on Chrome IMO, even if there's room for improvement.

**Review by neersighted — APPROVED** [review]

**Pull request merged**
